### ISSUE TITLE
Doesn't publish / return cursor

### ISSUE THREAD

**Issue by satyavh** [maximummeteor/server-transform#2]
Following the docs, if you try to return a cursor, nothing gets returned. Example:

```
  Posts.serverTransform(
     comments: (post) ->
      Comments.find(
        referenceId: post._id
      )
  )  
```

returns nothing. If you add `.fetch()` it does return the comments.

**Comment by maxnowack** [comment]
Can you provide a [meteorpad](http://meteorpad.com/) for this case?

**Comment by satyavh** [comment]
I understand how this works now. Closing this
