### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by wzalazar** [maximummeteor/server-transform#6]
Hi, today I work with meteor 1.2.1 version and I when add the package, show me that message.
File packages/maximum_reactive-cursors/reactive-cursors.coffee:59:29

**Comment by maxnowack** [comment]
In v0.5.0, I've removed the dependency to `maximum:reactive-cursors`. This package now use the `peerlibrary:reactive-mongo` package instead (as proposed in maximummeteor/reactive-cursors#2). Please check, if the bug still exists.
