### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by cyclops24** [maximummeteor/server-transform#7]
Hi @maxnowack,

First thanks for this awesome package. I use it in 5 project until now and it's work well.
I come here to thanks and tell some of dependency packages release new version and some changes so please update that dependency if you have time to keep this awesome package live.

Thanks for your attention.

**Comment by maxnowack** [comment]
Hey @cyclops24, is it possible for you to create a pull request with the updated dependencies?
That would be awesome :)

**Comment by cyclops24** [comment]
Hi @maxnowack I'm new in meteor package development but try to do this tomorrow.

**Comment by maxnowack** [comment]
awesome! feel free to ask, if you have any questions :)

**Comment by cyclops24** [comment]
Hi @maxnowack ,

Sorry for late reply. I upgrade dependency packages as [this pull request](https://github.com/maximummeteor/server-transform/pull/8). I'm not familiar with coffee-script and only change `package.js` file please check or test before accept this request.

Thanks for your attention man.

**Comment by cyclops24** [comment]
@maxnowack I can't update one of the function in extend.coffee file please see this if you have time because it's return this log:

`Meteor.addCollectionExtension` is deprecated, please use `CollectionExtensions.addExtension`
